name = "Quaternions"
uuid = "d5f8330d-dd38-4550-8d64-11a08a0c5416"
version = "0.1.0"
authors = ["F. Capolupo"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
